/**
 * Build runner. Produces a self-contained dist/ that the container runs:
 *   - frontend assets (vite build), with build-time prerendered HTML if this app prerenders
 *   - (server apps) the compiled server that serves the build and exposes the API
 */
import './load-env.mjs';
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolveBuildEnv } from './resolve-env.mjs';

const binDir = fileURLToPath(new URL('../node_modules/.bin/', import.meta.url));
/** Resolves a locally-installed CLI binary (Windows uses the .cmd shim). */
const bin = (name) => `${binDir}${name}${process.platform === 'win32' ? '.cmd' : ''}`;

function run(command, args) {
  const result = spawnSync(command, args, { stdio: 'inherit', shell: false });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

// Bake the server's environment identity. The compiled server imports src/env.generated.ts as a
// build-time constant (not a runtime env var), so it reports the environment this image was built
// for — matching what the frontend bundle bakes from the same APP_ENV_NAME. Overwrite it from the
// manifest before tsc compiles the server below. With no APP_ENV_NAME (local build) this writes the
// `local` identity, the same as the committed default.
const baked = resolveBuildEnv();
const generated = fileURLToPath(new URL('../src/env.generated.ts', import.meta.url));
// Emit a prettier-clean literal (unquoted keys, 2-space indent) so the generated file matches the
// committed default and passes the format gate without a post-step.
writeFileSync(
  generated,
  `/**\n` +
    ` * GENERATED by scripts/build.mjs from environments.json — the baked environment identity\n` +
    ` * for the compiled server. Do not hand-edit; edit environments.json instead.\n` +
    ` */\n` +
    `export const BAKED = {\n` +
    `  name: '${baked.name}',\n` +
    `  isPublicFace: ${baked.isPublicFace},\n` +
    `  noindex: ${baked.noindex},\n` +
    `} as const;\n`,
);

// Frontend build.
run(bin('vite'), ['build']);

// SPINUP:prerender-only:start
// Prerender build-time-known content into the emitted HTML. The web tsconfig selects
// the automatic JSX runtime so the React entries render under tsx.
run(bin('tsx'), ['--tsconfig', 'tsconfig.web.json', 'scripts/prerender.mjs']);
// SPINUP:prerender-only:end

// Compile the server that serves the build (static apps serve files; server apps
// also expose the API). Both modes ship this compiled server.
run(bin('tsc'), ['-p', 'tsconfig.build.json']);
