/**
 * GENERATED by scripts/build.mjs from environments.json — the baked environment identity
 * for the compiled server. Do not hand-edit; edit environments.json instead.
 */
export const BAKED = {
  name: 'local',
  isPublicFace: false,
  noindex: true,
} as const;
